algoritmo "EX_013"

var
    A, B, C : real
    S : real

inicio
      //entrada de dados - exercicio com operador de potencia
      escreva("Valor A: ")
      leia(A)
      
      escreva("Valor B: ")
      leia(B)
      
      escreva("Valor C: ")
      leia(C)
      
      //processamento - primeira solução
      
      S <- A^2 + B^2 + C^2
      
      //saída de dados
      escreva("Soma dos quadrados = ", S)
      
      
      

fimalgoritmo
