algoritmo "Ex.01_Lista03"


var

   i, soma : inteiro

inicio
   //inicialização
   //incremento
   //parada
   //usados quando usar enquanto e repita
   // i para iterar o laço de repetição, controladora
   //for para e while enquanto
   para i de 0 ate 20 faca
        se i mod 2 <> 0 entao
           soma <- soma + i
           escreval("Soma = ", soma)
        fimse
   
   fimpara
   
   escreval("Soma = ", soma)
   


fimalgoritmo
