algoritmo "Desafioaula8"


var
   n1, n2,  : inteiro
   

inicio

      //entrada de dados
      escreva("Digite um numero : ")
      leia (n1)
      
      escreva("Digite um numero : ")
      leia (n2)
      
      //processamento
      total <- n1 + n2
      escreval("Soma = ", total)
      
      total <- n1 - n2
      escreval("Subtracao = ", total)
      
      total <- n1 * n2
      escreval("Multiplicacao = ", total)

      //saída de dados



      
      
      


 
fimalgoritmo
