algoritmo "Matriz_Ex2"


var

   mat : vetor [0..1, 0..1] de inteiro
   i, j : inteiro
   

inicio

      para i de 0 ate 1 faca
           para j de 0 ate 1 faca
                escreva("Valor: ")
                leia( mat[i, j])
           fimpara
      fimpara
      

      
      //saída de dados
      para i de 0 ate 1 faca
           para j de 0 ate 1 faca
           escreval(mat[i, j])
           fimpara
      fimpara
      

fimalgoritmo
