algoritmo "Desafio10"

var

   A, B, C, h : real
inicio
      // entrada de dados
      escreva("Digite o valor da base maior: ")
      leia(B)
      
      escreva("Digite o valor da base menor: ")
      leia(C)
      
      escreva("Digite o valor da altura: ")
      leia(h)
      
      //processamento
      A <- ((B + C) / 2) * h
      
      //saída de dados
      escreval("A área do trapézio = ", A)
      
fimalgoritmo
